name: Auto-bump version on merge

# Se ejecuta sólo cuando hay push a la rama main
on:
  push:
    branches:
      - main

jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version (patch) & create tag
        id: tag
        uses: anothrNick/github-tag-action@v1.37.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Opcional: definir bump según mensaje de commit
        # with:
        #   default_bump: patch
        #   release_branches: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build Go binary
        run: |
          go build -o hello-go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: hello-go
          asset_path: ./hello-go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

